apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
nodes:
- role: control-plane
  image: @IMAGE@
- role: worker
  image: @IMAGE@
- role: worker
  image: @IMAGE@
- role: worker
  image: @IMAGE@
